### ISSUE TITLE
Multi-scale test is not complete

### ISSUE THREAD

**Issue by mengfanShi** [HRNet/HRNet-Bottom-Up-Pose-Estimation#1]
Glad to see your work, it's so great : )
But when i try to use multi-scale to test the model, it comes two problems:
1. the name of param is not the same as REDEME says, may be the SACLE_FACTOR;
2. i try to change value of SCALE_FACTOR, if scale num greater than 1, there would be an error that the dim is mismatch.
So i guess that the multi-scale test is not complete, or i didn't find the proper way to use it.
Looking forward for your reply, Thanks : )

**Comment by Gengzigang** [comment]
Hi mengfan,
Thanks for your kind issue. I have fixed the bugs of README and code.
