### ISSUE TITLE
How to train for multi-person detection?

### ISSUE THREAD

**Issue by OOF-dura** [HRNet/HRNet-Bottom-Up-Pose-Estimation#10]
I have a dataset which is with skeleton annotations.
However, there are multi-person. Not single person.
How can I train this?

I do not want to first detect the bounding box of the person.

**Comment by Gengzigang** [comment]
Our method does not need to detect the bounding box. For the testing case, you can run the tools/inference_demo.py to get the intuitive understand. For the training case, you can check issue #11 for the details.
