### ISSUE TITLE
What if the training pairs are without bbox?

### ISSUE THREAD

**Issue by Frank-Dz** [HRNet/HRNet-Bottom-Up-Pose-Estimation#11]
```
            area[i, 0] = obj['bbox'][2]*obj['bbox'][3]
```
This method requires bbox during training. What if the training pairs are without bbox?

How can we calculate the `area` and `loss of offset`?

**Comment by Gengzigang** [comment]
Hi, we use the area of one person's bounding box to normalize this person's offset during calculating the loss of the offset map. 
You can use the maximum and minimum coordinates of the key points to estimate the size of the people. The selection of this normalization tool doesn't influence the performance.

By the way, we use the average of all keypoints belong to the same person as the center of this person. In the code, we can choose the center of the person's bounding box as the center of this person, which may cause confusion. The APs of the two choices are the same.

**Comment by Frank-Dz** [comment]
yes.

But what if there are only one joint rather than 17 joints like coco?

How should we set the code?

Thanks!

**Comment by Frank-Dz** [comment]
> Hi, we use the area of one person's bounding box to normalize this person's offset during calculating the loss of the offset map.
> Alternatively, you can use the maximum and minimum coordinates of the key points to estimate the size of the people. The selection of this normalization tool doesn't influence the performance.
> 
> By the way, we use the average of all keypoints belong to the same person as the center of this person. In the code, we can choose the center of the person's bounding box as the center of this person, which may cause confusion. The APs of the two choices are the same.

For example, I just want to do head detection:
![image](https://user-images.githubusercontent.com/55009565/110122869-2a027700-7dfb-11eb-9796-7e03c0528ead.png)


My concern is that this will change the way we calculate the loss.

**Comment by Gengzigang** [comment]
The normalization tool should be designed for your project. You can use any length that reflects the size of the person, or you can directly regress the offsets without this normalization.

**Comment by Frank-Dz** [comment]
> The normalization tool should be designed for your project. You can use any length that reflects the size of the person, or you can directly regress the offsets without this normalization.

OK. I am trying the BBox generation based on the projection. But the BB is for the head rather than the whole body.

Thank you very much!

**Comment by Gengzigang** [comment]
> > The normalization tool should be designed for your project. You can use any length that reflects the size of the person, or you can directly regress the offsets without this normalization.
> 
> OK. I am trying the BBox generation based on the projection. But the BB is for the head rather than the whole body.
> 
> Thank you very much!

For your case, I think the heatmap is more suitable because you just need to detect the head keypoints and the heatmap can detect all the same kind of the keypoints precisely and efficiently.

**Comment by Frank-Dz** [comment]
> > > The normalization tool should be designed for your project. You can use any length that reflects the size of the person, or you can directly regress the offsets without this normalization.
> > 
> > 
> > OK. I am trying the BBox generation based on the projection. But the BB is for the head rather than the whole body.
> > Thank you very much!
> 
> For your case, I think the heatmap is more suitable because you just need to detect the head keypoints and the heatmap can detect all the same kind of the keypoints precisely and efficiently.

Sorry I just got confused about this:

![image](https://user-images.githubusercontent.com/55009565/110127325-77cdae00-7e00-11eb-81e1-e913946a76fa.png)

Do you mean we should just remove the offset loss?

**Comment by Gengzigang** [comment]
> > > > The normalization tool should be designed for your project. You can use any length that reflects the size of the person, or you can directly regress the offsets without this normalization.
> > > 
> > > 
> > > OK. I am trying the BBox generation based on the projection. But the BB is for the head rather than the whole body.
> > > Thank you very much!
> > 
> > 
> > For your case, I think the heatmap is more suitable because you just need to detect the head keypoints and the heatmap can detect all the same kind of the keypoints precisely and efficiently.
> 
> Sorry I just got confused about this:
> 
> ![image](https://user-images.githubusercontent.com/55009565/110127325-77cdae00-7e00-11eb-81e1-e913946a76fa.png)
> 
> Do you mean we should just remove the offset loss?
> Just use heatmap loss?

You can totally remove the offset regression part both in the training and post-processing. 

In this method, the offset means the location offset between the keypoint location and the center point location. However, in your case, I do not know how to choose the center point. I am curious about how do you use the offset regression.

**Comment by Frank-Dz** [comment]
> > > > > The normalization tool should be designed for your project. You can use any length that reflects the size of the person, or you can directly regress the offsets without this normalization.
> > > > 
> > > > 
> > > > OK. I am trying the BBox generation based on the projection. But the BB is for the head rather than the whole body.
> > > > Thank you very much!
> > > 
> > > 
> > > For your case, I think the heatmap is more suitable because you just need to detect the head keypoints and the heatmap can detect all the same kind of the keypoints precisely and efficiently.
> > 
> > 
> > Sorry I just got confused about this:
> > ![image](https://user-images.githubusercontent.com/55009565/110127325-77cdae00-7e00-11eb-81e1-e913946a76fa.png)
> > Do you mean we should just remove the offset loss?
> > Just use heatmap loss?
> 
> You can totally remove the offset regression part both in the training and post-processing.
> 
> In this method, the offset means the location offset between the keypoint location and the center point location. However, in your case, I do not know how to choose the center point. I am curious about how do you use the offset regression.

Yes! That's the point! Because in my case, I only want to detect the head. And there are many images without the full body. So the center position should be the **center of BBOX of head**. Yet this center position is quite close to the key point of head.
So maybe removing them is a good choice. 
Thank you again!

**Comment by Frank-Dz** [comment]
> > > > > The normalization tool should be designed for your project. You can use any length that reflects the size of the person, or you can directly regress the offsets without this normalization.
> > > > 
> > > > 
> > > > OK. I am trying the BBox generation based on the projection. But the BB is for the head rather than the whole body.
> > > > Thank you very much!
> > > 
> > > 
> > > For your case, I think the heatmap is more suitable because you just need to detect the head keypoints and the heatmap can detect all the same kind of the keypoints precisely and efficiently.
> > 
> > 
> > Sorry I just got confused about this:
> > ![image](https://user-images.githubusercontent.com/55009565/110127325-77cdae00-7e00-11eb-81e1-e913946a76fa.png)
> > Do you mean we should just remove the offset loss?
> > Just use heatmap loss?
> 
> You can totally remove the offset regression part both in the training and post-processing.
> 
> In this method, the offset means the location offset between the keypoint location and the center point location. However, in your case, I do not know how to choose the center point. I am curious about how do you use the offset regression.

**Comment by Frank-Dz** [comment]
> > > > > > The normalization tool should be designed for your project. You can use any length that reflects the size of the person, or you can directly regress the offsets without this normalization.
> > > > > 
> > > > > 
> > > > > OK. I am trying the BBox generation based on the projection. But the BB is for the head rather than the whole body.
> > > > > Thank you very much!
> > > > 
> > > > 
> > > > For your case, I think the heatmap is more suitable because you just need to detect the head keypoints and the heatmap can detect all the same kind of the keypoints precisely and efficiently.
> > > 
> > > 
> > > Sorry I just got confused about this:
> > > ![image](https://user-images.githubusercontent.com/55009565/110127325-77cdae00-7e00-11eb-81e1-e913946a76fa.png)
> > > Do you mean we should just remove the offset loss?
> > > Just use heatmap loss?
> > 
> > 
> > You can totally remove the offset regression part both in the training and post-processing.
> > In this method, the offset means the location offset between the keypoint location and the center point location. However, in your case, I do not know how to choose the center point. I am curious about how do you use the offset regression.
> 
> Yes! That's the point! Because in my case, I only want to detect the head. And there are many images without the full body. So the center position should be the **center of BBOX of head**. Yet this center position is quite close to the key point of head.
> So maybe removing them is a good choice.
> Thank you again!

Hi May I know is there a way to train the NN on a ~20 GB  GPU? 
All current NNs are too big for my GPUs (2 Nvidia 2080).

**Comment by Frank-Dz** [comment]
> > > > > The normalization tool should be designed for your project. You can use any length that reflects the size of the person, or you can directly regress the offsets without this normalization.
> > > > 
> > > > 
> > > > OK. I am trying the BBox generation based on the projection. But the BB is for the head rather than the whole body.
> > > > Thank you very much!
> > > 
> > > 
> > > For your case, I think the heatmap is more suitable because you just need to detect the head keypoints and the heatmap can detect all the same kind of the keypoints precisely and efficiently.
> > 
> > 
> > Sorry I just got confused about this:
> > ![image](https://user-images.githubusercontent.com/55009565/110127325-77cdae00-7e00-11eb-81e1-e913946a76fa.png)
> > Do you mean we should just remove the offset loss?
> > Just use heatmap loss?
> 
> You can totally remove the offset regression part both in the training and post-processing.
> 
> In this method, the offset means the location offset between the keypoint location and the center point location. However, in your case, I do not know how to choose the center point. I am curious about how do you use the offset regression.

Hi~ Still get a little confused. Really sorry to bother you. 
Seems like the method still need nonmaximum suppression to filter the Redundant BBox.
I have train the NN to predict only one point in the heatmap. How can we avoid the nonmaximum suppression which get **BBox** and **offset** involved? (In other words, we do not need to group the people, since there is only one point for each person.) Any suggestions?
![image](https://user-images.githubusercontent.com/55009565/111014212-a7228300-83dd-11eb-80b0-bcc0c0264992.png)

**Comment by Frank-Dz** [comment]
Actually, https://openaccess.thecvf.com/content_CVPR_2019/html/Ribera_Locating_Objects_Without_Bounding_Boxes_CVPR_2019_paper.html
There is a paper quite close to my situation where they do obj detection without Bbox. 
But I hope to use the heatmap to do so since I think this will provide a more stable result.
