### ISSUE TITLE
Train with no bounding box dataset

### ISSUE THREAD

**Issue by gondimjoaom** [HRNet/HRNet-Bottom-Up-Pose-Estimation#2]
Hi! First of all: congratulations for the amazing work!

This is not an issue per say, but a have a dataset generated from openpose that gives me all keypoints from people in my videos, but no bounding boxes.

Is there a way to train your neural network with a ['bbox'] =[] key inside my jsons?

**Comment by Gengzigang** [comment]
Hi, I understand that you need to jointly train pose estimation and person detection.
Unfortunately, the code is only for the bottom-up pose estimation which doesn't need bounding boxes.

**Comment by gondimjoaom** [comment]
Got it. So this is the misconception I had. HRNet-Bottom-Up-Pose-Estimation is a bottom up approach used for pose estimation, but I still have to give as input a cropped image of a person located somewhere inside my whole frame. Is that correct?

**Comment by Gengzigang** [comment]
I guess you still have misconception. The input of bottom-up pose estimation is a natural image and the output is all keypoint coordinates in the image. You can run the tools/inference_demo.py to get the intuitive understand.

**Comment by gondimjoaom** [comment]
Thank you so much for taking some of your time to explain this. Appreciate it :)

I will close the issue now.

**Comment by Frank-Dz** [comment]
> I guess you still have misconception. The input of bottom-up pose estimation is a natural image and the output is all keypoint coordinates in the image. You can run the tools/inference_demo.py to get the intuitive understand.

Hi. I think you are using bounding box during training:
![image](https://user-images.githubusercontent.com/55009565/110109802-e737a380-7de8-11eb-938c-8ee2dff1ede5.png)

How can we train the NN without this BBox information?

**Comment by Frank-Dz** [comment]
Both training on COCO and CrowdPose require the BBox annotation.

See my issue here: 
https://github.com/HRNet/HRNet-Bottom-Up-Pose-Estimation/issues/11

**Comment by Frank-Dz** [comment]
> Thank you so much for taking some of your time to explain this. Appreciate it :)
> 
> I will close the issue now.

Hi, did you solve the problem?

![image](https://user-images.githubusercontent.com/55009565/110110432-c885dc80-7de9-11eb-8a12-8656c7204f4e.png)

The problem is, during training, you still need to load the bbox.
