### ISSUE TITLE
[UNMATCHING FILTER COUNT] Crowdpose model does not load

### ISSUE THREAD

**Issue by rosivagyok** [HRNet/HRNet-Bottom-Up-Pose-Estimation#3]
Hi.

First of all thank you very much for your work, great pose estimation libary!

When I would like to test your crowdpose trained models, I get the following error:

`root@lsdl030x:/workspace# python tools/inference_demo.py --cfg experiments/inference_demo.yaml --videoFile crowd_issue_example.mp4 --outputDir output --visthre 0.3 TEST.MODEL_FILE model/pose_crowdpose/pose_hrnet_w32_reg_delaysep_bg01_stn_512_adam_lr1e-3_crowdpose_x300.pth

=> loading model from model/pose_crowdpose/pose_hrnet_w32_reg_delaysep_bg01_stn_512_adam_lr1e-3_crowdpose_x300.pth
Traceback (most recent call last):

  File "tools/inference_demo.py", line 267, in <module>
    main()
  File "tools/inference_demo.py", line 190, in main
    cfg.TEST.MODEL_FILE), strict=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PoseHigherResolutionNet:
        size mismatch for transition_reg.0.weight: copying a param with shape torch.Size([256, 494, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 497, 1, 1]).
        size mismatch for final_layers.0.weight: copying a param with shape torch.Size([14, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([17, 32, 1, 1]).
        size mismatch for final_layers.0.bias: copying a param with shape torch.Size([14]) from checkpoint, the shape in current model is torch.Size([17]).
        size mismatch for final_layers.1.weight: copying a param with shape torch.Size([29, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([35, 256, 1, 1]).
        size mismatch for final_layers.1.bias: copying a param with shape torch.Size([29]) from checkpoint, the shape in current model is torch.Size([35]).`

It seems like PyTorch was unable to load the model weights, to the defined model, because unmatching layer dimensions. I followed your installation instructions throughly and I can test the coco trained models.

Do you have any idea why this occurs or can you guide me towards solving this issue? Thank you in advance!

Peter

**Comment by Gengzigang** [comment]
Hi,
Thanks for your kind issue. The problem is caused by the following reason. Each person in the COCO dataset has 17 keypoints, while each person in CrowdPose dataset has 14 keypoints. So, the models for two datasets are different and have different dimension. If you want to use CrowdPose model to visualize the results, you can just change MODEL.NUM_JOINTS and DATASET.NUM_JOINTS in inference_demo.yaml to 14. I will add this feature as soon as possible. 

Zigang

**Comment by Gengzigang** [comment]
Hi,
I have added this feature just now. Please see the commit "inference_demo supports CrowdPose model". Thanks for your issue.

Zigang

**Comment by rosivagyok** [comment]
Thanks for the quick fix, much appreciated!
