### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by jinleibupt** [HRNet/HRNet-Bottom-Up-Pose-Estimation#4]
I retrain your model, but I found the model can't get 67.3 with single scale. (ps. I only get 60.9 without the rescore model) Can you present more training detials?  Thanks!

**Comment by Gengzigang** [comment]
We trained the model using 4 NVIDIA V100 GPU and this config file (experiments/crowdpose/w32/w32_4x_reg_delaysep_bg01_stn_512_adam_lr1e-3_crowdpose_x300.yaml) to get 67.3AP in COCO dataset. I would like to ask what changes have you made to this file?

**Comment by jinleibupt** [comment]
I did't change this file.  However, I used 8 gpu. I found there is no val process in your training code.  (ps. I add a val process in my code can improve the result, but still can't get 67.3AP)

**Comment by Gengzigang** [comment]
You can use tools/valid.py to evaluate your model.  I think the poor performance is might caused by the post-processing.
