### ISSUE TITLE
Question with GFLOPs

### ISSUE THREAD

**Issue by shen494157765** [HRNet/HRNet-Bottom-Up-Pose-Estimation#5]
Hi,

When I check the GFLOPs with the model, I found that the model with **pose_hrnet_w32** backbone and **512 512** input size only have 45.03 GFLOPs.

But it showed 63.7 GFLOPs in your repo, so I am a little confused with it.

If I was wrong, please tell me how to fix it.

Thanks

**Comment by shen494157765** [comment]
By the way, I used ptflops to calculate the GFLOPs, and got 45.03 GFLOPs.
However, when I used thop, I got 44.90 GFLOPs and got some warning:

[WARN] Cannot find rule for <class 'torch.nn.modules.container.Sequential'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'lib.models.conv_module.Bottleneck'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.modules.container.ModuleList'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'lib.models.conv_module.BasicBlock'>. Treat it as zero Macs and zero Params.

[WARN] Cannot find rule for <class 'lib.models.conv_module.HighResolutionModule'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'lib.models.dcn.deform_conv.DeformConv'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'lib.models.conv_module.STNBLOCK'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'lib.models.pose_hrnet.PoseHigherResolutionNet'>. Treat it as zero Macs and zero Params.

I have no idea that if it is the problem which caused the difference

**Comment by Gengzigang** [comment]
Hi,

Now, we add the GFLOPS calculation function to the code and you can see the commit "add calculation of params and GFlops". I think the reason that GFLOPs that you calculated is wrong is that the tools don't consider the GFLOPs of deformable convolution. 

Thanks.
