### ISSUE TITLE
what is the role of the 'rescore' model ?

### ISSUE THREAD

**Issue by yxxxqqq** [HRNet/HRNet-Bottom-Up-Pose-Estimation#6]
sorry to bother you, but I don't really understand the meaning of the 'rescore' part: score data? training rescore model ?

**Comment by Gengzigang** [comment]
Hi,

It's a post-process. The rescore model is using a MLP to predict the more precise score of a pose. You can find the details at inference part (Section3.2) in the paper (https://arxiv.org/pdf/2006.15480.pdf).

Zigang
