### ISSUE TITLE
perf_indicator and best_perf update problem

### ISSUE THREAD

**Issue by vvhj** [HRNet/HRNet-Bottom-Up-Pose-Estimation#8]
Hi！
I doubt the train.py: 
line 258: 
perf_indicator = epoch

but in the line 251:
for epoch in range(begin_epoch, cfg.TRAIN.END_EPOCH)

Do you mean that after training, no test is performed to select the best model and the latest model defaults as the best model?

**Comment by Gengzigang** [comment]
Yes, we just use the latest model as the best model.
