### ISSUE TITLE
Pose estimation on cropped BB

### ISSUE THREAD

**Issue by AvivSham** [HRNet/HRNet-Bottom-Up-Pose-Estimation#9]
Hi all,
Thank you for your excellent work and for sharing your code and models. I want to use your model as part of my system, here is the system's description:
Input ---> Person Object Detection ---> Pose estimation for each detected BB ---> further analysis ---> output

I want to extract pose estimation for each BB but I think I will encounter two problems:
1) As most DL models, since BB is much smaller than the image sizes you trained your model on it won't perform well. (This is a common generalization problem in DL)
2) BBs may differ in size with can cause a discrepancy for the model.

I thought of one solution where I can pad each BB to match the size you trained your model on, but I thought there must be a more elegant way to approach this.
Have you tried to tackle such problem? Do you have a suggestion for me?

Cheers.

**Comment by welleast** [comment]
Thanks Avivsham! 

According to your description, in your system, the person box will be detected. So you need to check the top-down approach: https://github.com/leoxiaobin/deep-high-resolution-net.pytorch.

Thanks

**Comment by AvivSham** [comment]
@welleast Thank you for your response.
 - Can you please elaborate on the differences between top-down and bottom-up? (my guess is that bottom up refers to first do the pose estimation and then the detection)
 - It didn't answer my question on how to deal with different BB size / input size (compare to training)

**Comment by welleast** [comment]
- The differences you guessed are correct.
- Just normalize the BB to a fixed size same with the training size.

**Comment by AvivSham** [comment]
- About your second point, as I said -  "I thought of one solution where I can pad each BB to match the size you trained your model on, but I thought there must be a more elegant way to approach this." I guess there is no more elegant way, is that your point?

**Comment by welleast** [comment]
Maybe there is a more elegant way. Will figure out it...
